require:
  - rubocop-performance

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.1
  DisabledByDefault: true
  Exclude:
    - "gemfiles/**/*"

Bundler:
  Enabled: true

Gemspec:
  Enabled: true

Layout:
  Enabled: true

Layout/LineLength:
  Max: 120

Lint:
  Enabled: true

Naming:
  Enabled: true

Performance:
  Enabled: true

Security:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true

Style/HashSyntax:
  Enabled: true

Style/RedundantFreeze:
  Enabled: true
