#!/bin/sh

set -x

if apt-cache show libcbor-dev >> /dev/null; then
  echo "libcbor-dev is avialable in apt sources";
else
  add-apt-repository ppa:yubico/stable -y
  apt-get update -q
fi

apt-get install libcbor-dev -y
