# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: build

on: push

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 3.3
          - 3.2
          - 3.1
          - 3.0.0
          - 2.7.2
          - 2.6.6
          - 2.5.8
          - 2.4.10
        gemfile:
          - openssl_3_0
          - openssl_2_2
          - openssl_2_1
          - openssl_default
        exclude:
          - ruby: '2.4.10'
            gemfile: openssl_3_0
          - ruby: '2.5.8'
            gemfile: openssl_3_0
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rake
